### ISSUE TITLE
nodeList forEach() not widely supported

### ISSUE THREAD

**Issue by DorianVasco** [johnsonjo4531/videojs-gifplayer#1]
I get an error on Chrome and a crash on IE on this line:
451:   gifPlayers.forEach(function gifPlayerHandler(gifPlayer) {

see here: http://stackoverflow.com/a/10493129

a fast fix was to prepend
  gifPlayers = Array.prototype.slice.call(gifPlayers);

**Comment by johnsonjo4531** [comment]
Let me know if that commit fixed your issue. It should be fixed in the latest version.

**Comment by johnsonjo4531** [comment]
@DorianVasco Closing this for now, let me know if that commit didn't fix your issue.
